// Code generated by protoc-gen-gocraft. DO NOT EDIT.
//
// Source: abi/v1/events.proto

package plugin

import (
	"GoCraft/core/player"
	"GoCraft/core/spatial"
	coreworld "GoCraft/core/world"
	abi "github.com/GoCraft-MC/gocraft-abi/abi/v1"
)

// Event types, as a manifest spells them.
const (
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventBlockBreak = "block.break"
	// Observational, never cancelled. Introduced in ABI 1.
	EventPlayerJoin = "player.join"
)

// IsNativeEvent reports whether the host itself emits this event.
//
// Anything else a manifest names has to be a plugin-defined type. If no
// scanned manifest provides one, the subscription is a typo that would
// otherwise load cleanly and never fire.
func IsNativeEvent(eventType string) bool {
	switch eventType {
	case EventBlockBreak, EventPlayerJoin:
		return true
	}
	return false
}

// NativeEvents lists them, in schema order, for a message that has to tell
// someone what they could have subscribed to.
//
// A fresh slice every call: the host's vocabulary is fixed at build time and
// no caller may extend it.
func NativeEvents() []string {
	return []string{EventBlockBreak, EventPlayerJoin}
}

// BlankEvent is a payload of one native event's shape, carrying nothing.
//
// Shape and never content — an empty name, a zero, a player who is nobody
// — because nothing built from this is meant to be read as data. It is
// sent in a warm dispatch and reaches no handler.
//
// Nil for a type this host does not emit, which is the honest answer for a
// plugin-defined event: its shape is in the manifest that declared it.
func BlankEvent(eventType string) []abi.Value {
	switch eventType {
	case EventBlockBreak:
		return []abi.Value{
			abi.List(abi.Bytes(make([]byte, 16)), abi.String(""), abi.String("")),
			abi.List(abi.Int64(0), abi.Int64(0), abi.Int64(0)),
			abi.List(abi.String(""), abi.List()),
			abi.String(""),
			abi.List(abi.List(abi.String(""), abi.Bool(false))),
		}
	case EventPlayerJoin:
		return []abi.Value{
			abi.List(abi.Bytes(make([]byte, 16)), abi.String(""), abi.String("")),
			abi.List(abi.List(abi.String(""), abi.Bool(false))),
		}
	}
	return nil
}

// EmitBlockBreak publishes block.break to every subscriber, in the same shape whatever
// edition the player is on and whatever runtime the plugin uses.
//
// It blocks the tick under the budget shared by every subscriber, and reports
// whether the action may proceed. A false return means a plugin refused it.
func (b *Bus) EmitBlockBreak(playerRef *player.Player, pos spatial.BlockPos, block coreworld.Block, tool string) bool {
	if !b.hasSubscribers(EventBlockBreak) {
		return true
	}
	event := &abi.Event{
		Type:      EventBlockBreak,
		OnFailure: abi.FailureAllow,
		Fields: []abi.Value{
			playerReference(playerRef),
			positionValue(pos),
			blockValue(block),
			abi.String(tool),
			b.injectedPermissions(EventBlockBreak, playerRef),
		},
	}
	return b.EmitCancellable(event)
}

// EmitPlayerJoin publishes player.join to every subscriber, in the same shape whatever
// edition the player is on and whatever runtime the plugin uses.
//
// Observational: the tick does not wait, and nothing a subscriber does can
// prevent what already happened.
func (b *Bus) EmitPlayerJoin(playerRef *player.Player) {
	if !b.hasSubscribers(EventPlayerJoin) {
		return
	}
	event := &abi.Event{
		Type:      EventPlayerJoin,
		OnFailure: abi.FailureAllow,
		Fields: []abi.Value{
			playerReference(playerRef),
			b.injectedPermissions(EventPlayerJoin, playerRef),
		},
	}
	b.EmitObservational(event)
}

// EmitPlayerJoinTo replays player.join to named plugins only.
//
// For a runtime that died and was brought back: its plugins missed what
// happened while they were down, and the ones that stayed up did not.
func (b *Bus) EmitPlayerJoinTo(plugins []string, playerRef *player.Player) {
	if len(plugins) == 0 {
		return
	}
	event := &abi.Event{
		Type:      EventPlayerJoin,
		OnFailure: abi.FailureAllow,
		Fields: []abi.Value{
			playerReference(playerRef),
			b.injectedPermissions(EventPlayerJoin, playerRef),
		},
	}
	b.EmitObservationalTo(event, plugins)
}
