package main

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateGo writes the host side: one type constant and one typed emitter per
// event.
//
// It replaces what used to be hand-written. Keeping both would mean the Go
// payload and the Java accessors could disagree about what index 3 holds, and
// nothing would notice until a handler read the wrong field — which is the
// drift §01 exists to prevent.
//
// The emitters call hand-written vocabulary helpers rather than inlining the
// conversions, because those are the fifteen types where generated code would
// be mediocre.
func generateGo(plugin *protogen.Plugin, events []event) error {
	file := plugin.NewGeneratedFile("core/plugin/events.gen.go", "GoCraft/core/plugin")

	file.P("// Code generated by protoc-gen-gocraft. DO NOT EDIT.")
	file.P("//")
	file.P("// Source: abi/v1/events.proto")
	file.P()
	file.P("package plugin")
	file.P()
	file.P("import (")
	for _, line := range imports(events) {
		file.P("	" + line)
	}
	file.P(")")
	file.P()

	file.P("// Event types, as a manifest spells them.")
	file.P("const (")
	for _, declared := range events {
		file.P(fmt.Sprintf("\t// %s. Introduced in ABI %d.", describe(declared), declared.Since))
		file.P(fmt.Sprintf("\t%s = %q", declared.ConstName(), declared.Type))
	}
	file.P(")")
	file.P()

	nativeEventPredicate(file, events)
	if err := blankPayloads(file, events); err != nil {
		return err
	}

	for _, declared := range events {
		if err := emitter(file, declared); err != nil {
			return err
		}
	}

	return nil
}

// blankPayloads emits a payload of each native event's own shape, carrying
// nothing.
//
// It is what a warm dispatch sends. The first event to carry values costs about
// two milliseconds once per process — the marshal here, the protobuf parse in
// the runtime, the conversion back into something a handler could read — and
// that lands on whichever real event happens to be first, out of a budget
// shared by every subscriber. Sent from here instead, before READY, where the
// host is waiting anyway and no budget is running.
//
// Built on this side rather than by the runtime receiving it, and that is the
// whole point: a blank the runtime made for itself never crosses the socket, so
// the path that carries values stays exactly as cold as it was. The first
// attempt at this did precisely that and moved nothing.
//
// Generated, because the shape is the schema's. A list written by hand beside
// the vocabulary would drift the day a field is added, and a blank of the wrong
// shape is worse than none: every decoder on the far side refuses a kind it
// does not expect and falls back, so it would warm the refusal.
func blankPayloads(file *protogen.GeneratedFile, events []event) error {
	file.P("// BlankEvent is a payload of one native event's shape, carrying nothing.")
	file.P("//")
	file.P("// Shape and never content — an empty name, a zero, a player who is nobody")
	file.P("// — because nothing built from this is meant to be read as data. It is")
	file.P("// sent in a warm dispatch and reaches no handler.")
	file.P("//")
	file.P("// Nil for a type this host does not emit, which is the honest answer for a")
	file.P("// plugin-defined event: its shape is in the manifest that declared it.")
	file.P("func BlankEvent(eventType string) []abi.Value {")
	file.P("	switch eventType {")
	for _, declared := range events {
		file.P(fmt.Sprintf("	case %s:", declared.ConstName()))
		file.P("		return []abi.Value{")
		for _, f := range declared.Fields {
			if f.Injected {
				file.P("			" + permissionsBlank + ",")
				continue
			}
			bound, err := bindingFor(f.Kind)
			if err != nil {
				return fmt.Errorf("%s.%s: %w", declared.Type, f.Name, err)
			}
			file.P("			" + bound.GoBlank + ",")
		}
		file.P("		}")
	}
	file.P("	}")
	file.P("	return nil")
	file.P("}")
	file.P()
	return nil
}

// nativeEventPredicate emits the closed set of events the host itself emits.
//
// Generated rather than written beside the vocabulary, because it is only worth
// anything if it is exhaustive: a hand-kept list that misses the next native
// event refuses a subscription that would have worked, which is worse than not
// checking at all. Both forms come out of the same slice here, so the predicate
// and the listing cannot disagree either.
func nativeEventPredicate(file *protogen.GeneratedFile, events []event) {
	names := make([]string, 0, len(events))
	for _, declared := range events {
		names = append(names, declared.ConstName())
	}
	joined := strings.Join(names, ", ")

	file.P("// IsNativeEvent reports whether the host itself emits this event.")
	file.P("//")
	file.P("// Anything else a manifest names has to be a plugin-defined type. If no")
	file.P("// scanned manifest provides one, the subscription is a typo that would")
	file.P("// otherwise load cleanly and never fire.")
	file.P("func IsNativeEvent(eventType string) bool {")
	if len(names) == 0 {
		file.P("	return false")
	} else {
		file.P("	switch eventType {")
		file.P("	case " + joined + ":")
		file.P("		return true")
		file.P("	}")
		file.P("	return false")
	}
	file.P("}")
	file.P()

	file.P("// NativeEvents lists them, in schema order, for a message that has to tell")
	file.P("// someone what they could have subscribed to.")
	file.P("//")
	file.P("// A fresh slice every call: the host's vocabulary is fixed at build time and")
	file.P("// no caller may extend it.")
	file.P("func NativeEvents() []string {")
	file.P("	return []string{" + joined + "}")
	file.P("}")
	file.P()
}

// imports lists the vocabulary packages this event set needs, sorted and
// deduplicated.
//
// Computed rather than fixed: a list written by hand breaks the day a schema
// drops its last BlockPos, and padding it with blank identifiers to stop that
// is worse than working it out.

// abiImport is where the shared types live, now that they are their own module.
const abiImport = `abi "github.com/GoCraft-MC/gocraft-abi/abi/v1"`

// importPath is the quoted path of an import line, alias or not.
func importPath(line string) string {
	start, end := strings.Index(line, `"`), strings.LastIndex(line, `"`)
	if start < 0 || end <= start {
		return line
	}
	return line[start+1 : end]
}
func imports(events []event) []string {
	// The ABI is always imported: every emitter takes an abi.Event apart.
	seen := map[string]struct{}{abiImport: {}}
	lines := []string{abiImport}
	for _, declared := range events {
		for _, f := range declared.Fields {
			if f.Injected {
				continue
			}
			bound, err := bindingFor(f.Kind)
			if err != nil || bound.GoImport == "" {
				continue
			}
			if _, duplicate := seen[bound.GoImport]; duplicate {
				continue
			}
			seen[bound.GoImport] = struct{}{}
			lines = append(lines, bound.GoImport)
		}
	}
	// By path rather than by line, because an aliased import starts with its
	// alias and would sort where the alias falls. gofmt sorts by path, and a
	// generated file it would reformat is a file the next regeneration undoes.
	sort.Slice(lines, func(i, j int) bool { return importPath(lines[i]) < importPath(lines[j]) })
	return lines
}

func emitter(file *protogen.GeneratedFile, declared event) error {
	parameters := make([]string, 0, len(declared.Fields))
	values := make([]string, 0, len(declared.Fields))
	var actor string

	for _, f := range declared.Fields {
		if f.Injected {
			// The host resolves this rather than being handed it, which is
			// what lets a handler answer can() without a round trip.
			values = append(values, fmt.Sprintf("b.injectedPermissions(%s, %s)",
				declared.ConstName(), actorOr(actor)))
			continue
		}
		bound, err := bindingFor(f.Kind)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", declared.Type, f.Name, err)
		}
		name := parameterName(f)
		parameters = append(parameters, name+" "+bound.GoType)
		values = append(values, fmt.Sprintf(bound.GoEncode, name))
		if f.Kind == "PlayerRef" && actor == "" {
			actor = name
		}
	}

	file.P(fmt.Sprintf("// %s publishes %s to every subscriber, in the same shape whatever",
		declared.EmitName(), declared.Type))
	file.P("// edition the player is on and whatever runtime the plugin uses.")
	if declared.Cancellable {
		file.P("//")
		file.P("// It blocks the tick under the budget shared by every subscriber, and reports")
		file.P("// whether the action may proceed. A false return means a plugin refused it.")
	} else {
		file.P("//")
		file.P("// Observational: the tick does not wait, and nothing a subscriber does can")
		file.P("// prevent what already happened.")
	}

	signature := fmt.Sprintf("func (b *Bus) %s(%s)", declared.EmitName(), strings.Join(parameters, ", "))
	if declared.Cancellable {
		signature += " bool"
	}
	file.P(signature + " {")

	// An event with no subscriber costs not one serialization. The bus would
	// reach the same answer, but only after building a payload nobody wants.
	if declared.Cancellable {
		file.P(fmt.Sprintf("\tif !b.hasSubscribers(%s) {", declared.ConstName()))
		file.P("\t\treturn true")
		file.P("\t}")
	} else {
		file.P(fmt.Sprintf("\tif !b.hasSubscribers(%s) {", declared.ConstName()))
		file.P("\t\treturn")
		file.P("\t}")
	}

	file.P("\tevent := &abi.Event{")
	file.P(fmt.Sprintf("\t\tType:      %s,", declared.ConstName()))
	file.P(fmt.Sprintf("\t\tOnFailure: abi.Failure%s,", declared.OnFailure))
	file.P("\t\tFields: []abi.Value{")
	for _, value := range values {
		file.P("\t\t\t" + value + ",")
	}
	file.P("\t\t},")
	file.P("\t}")
	if declared.Cancellable {
		file.P("\treturn b.EmitCancellable(event)")
	} else {
		file.P("\tb.EmitObservational(event)")
	}
	file.P("}")
	file.P()

	if declared.Observational {
		replay(file, declared, parameters, values)
	}
	return nil
}

// replay emits the targeted variant, for observational events only.
//
// A runtime that died and came back has plugins that missed everything while
// they were down. The ones that never went away did not, and delivering it to
// them too would have a Lua plugin count arrivals that never happened every
// time the JVM crashes.
//
// Cancellable events get no such variant. Replaying a question the host already
// answered would invite an answer nothing can act on.
func replay(file *protogen.GeneratedFile, declared event, parameters, values []string) {
	file.P(fmt.Sprintf("// %sTo replays %s to named plugins only.",
		declared.EmitName(), declared.Type))
	file.P("//")
	file.P("// For a runtime that died and was brought back: its plugins missed what")
	file.P("// happened while they were down, and the ones that stayed up did not.")
	file.P(fmt.Sprintf("func (b *Bus) %sTo(plugins []string, %s) {",
		declared.EmitName(), strings.Join(parameters, ", ")))
	file.P("\tif len(plugins) == 0 {")
	file.P("\t\treturn")
	file.P("\t}")
	file.P("\tevent := &abi.Event{")
	file.P(fmt.Sprintf("\t\tType:      %s,", declared.ConstName()))
	file.P(fmt.Sprintf("\t\tOnFailure: abi.Failure%s,", declared.OnFailure))
	file.P("\t\tFields: []abi.Value{")
	for _, value := range values {
		file.P("\t\t\t" + value + ",")
	}
	file.P("\t\t},")
	file.P("\t}")
	file.P("\tb.EmitObservationalTo(event, plugins)")
	file.P("}")
	file.P()
}

// actorOr names the player a permission map is resolved against. An event with
// no player resolves against none, and every node reads as false — which is
// correct: there is nobody to hold one.
func actorOr(actor string) string {
	if actor == "" {
		return "nil"
	}
	return actor
}

func describe(declared event) string {
	if declared.Observational {
		return "Observational, never cancelled"
	}
	if declared.Cancellable {
		return "Cancellable, blocks the tick, defaults to " + strings.ToLower(declared.OnFailure)
	}
	return "Blocks the tick"
}

func lowerFirst(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}

// reservedGoNames are the packages the generated file imports. A parameter
// taking one of these names still compiles — the type in the signature is
// resolved before the parameter is in scope — but it shadows the package inside
// the body, which is exactly the kind of thing that reads as correct until
// somebody adds a line that needs the package.
var reservedGoNames = map[string]struct{}{
	"abi": {}, "player": {}, "spatial": {}, "coreworld": {},
}

func parameterName(f field) string {
	name := lowerFirst(f.GoName())
	if _, reserved := reservedGoNames[name]; reserved {
		return name + "Ref"
	}
	return name
}
