package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateSDK writes the plugin side of the Go runtime: the event a handler
// receives, the typed registration that hands it over, and the decoder that
// reads it off the wire.
//
// It exists because the SDK used to be a transcription. The host emitters and
// the Java classes came out of this schema, and a Go plugin's view of the same
// events was maintained by hand beside them — so it had already drifted:
// block positions narrowed to 32 bits the schema declares as 64, and the
// injected permission map was a public field where the schema says it must be
// a query method. Neither would ever have failed a build.
//
// Vocabulary stays hand-written on both sides, as §03 draws the line. What is
// generated is the ~150 events built out of it.
func generateSDK(plugin *protogen.Plugin, events []event) error {
	// The SDK is its own module now, so the path is relative to wherever the
	// template points -o, and the Go import path is the one a plugin author
	// writes.
	file := plugin.NewGeneratedFile("events.gen.go", "github.com/GoCraft-MC/gocraft-api-go")

	file.P("// Code generated by protoc-gen-gocraft. DO NOT EDIT.")
	file.P("//")
	file.P("// Source: abi/v1/events.proto")
	file.P()
	file.P("package gocraft")
	file.P()
	file.P("import (")
	file.P("	\"fmt\"")
	file.P()
	file.P("	abi \"github.com/GoCraft-MC/gocraft-abi/abi/v1\"")
	file.P(")")
	file.P()

	file.P("// Event types, as a manifest spells them.")
	file.P("const (")
	for _, declared := range events {
		file.P(fmt.Sprintf("\t// %s. Introduced in ABI %d.", describe(declared), declared.Since))
		file.P(fmt.Sprintf("\t%s = %q", declared.ConstName(), declared.Type))
	}
	file.P(")")
	file.P()

	for _, declared := range events {
		if err := sdkEvent(file, declared); err != nil {
			return err
		}
	}
	return sdkDispatch(file, events)
}

// sdkEvent writes one event: its struct, what it answers, and how it is
// registered for.
func sdkEvent(file *protogen.GeneratedFile, declared event) error {
	class := declared.SDKType()

	file.P(fmt.Sprintf("// %s is the %s event.", class, declared.Type))
	file.P("//")
	for _, line := range strings.Split(sdkDoc(declared), "\n") {
		file.P("// " + line)
	}
	file.P(fmt.Sprintf("type %s struct {", class))
	for _, f := range declared.Payload() {
		binding, err := bindingFor(f.Kind)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", declared.Type, f.Name, err)
		}
		if binding.SDKType == "" {
			return fmt.Errorf("%s.%s: no plugin-side Go type for %q; add one to "+
				"cmd/protoc-gen-gocraft/vocabulary.go", declared.Type, f.Name, f.Kind)
		}
		file.P(fmt.Sprintf("\t%s %s", f.GoName(), binding.SDKType))
	}
	if _, ok := declared.Permissions(); ok {
		file.P()
		file.P("\t// permissions is what the host resolved before dispatch. Unexported")
		file.P("\t// because the schema says an injected field surfaces as a query")
		file.P("\t// rather than as a map to rummage through, and because a handler")
		file.P("\t// that could write to it would be answering its own question.")
		file.P("\tpermissions map[string]bool")
	}
	file.P("}")
	file.P()

	file.P(fmt.Sprintf("func (*%s) Type() string { return %s }", class, declared.ConstName()))
	file.P()

	if _, ok := declared.Permissions(); ok {
		file.P("// Can reports whether the acting player holds a permission node.")
		file.P("//")
		file.P("// Already resolved: the host answers every node the manifest subscribed")
		file.P("// to and ships the answers inside the event, so this is a map lookup")
		file.P("// rather than a round trip taken while the tick waits.")
		file.P("//")
		file.P("// A node the manifest never declared reads false, because the host was")
		file.P("// never asked about it. That is a manifest bug, not a denial.")
		file.P(fmt.Sprintf("func (e *%s) Can(node string) bool { return e.permissions[node] }", class))
		file.P()
	}

	file.P(fmt.Sprintf("// %s registers a handler for %s.", declared.SDKRegister(), declared.Type))
	file.P("//")
	file.P("// Typed, so there is no event name to misspell: the parameter is the")
	file.P("// subscription. On accepts a name for anything this build does not know.")
	file.P("//")
	file.P("// The control is what a handler refuses with, and where it reaches a")
	file.P("// player the event did not hand it. A handler that only watches may")
	file.P("// ignore it; it is a parameter rather than a method on the event because")
	file.P("// a plugin-defined event is a struct its author wrote, and one shape for")
	file.P("// both beats two that differ by who wrote the event.")
	file.P(fmt.Sprintf("func (e *Events) %s(handler func(*%s, EventControl)) error {",
		declared.SDKRegister(), class))
	file.P(fmt.Sprintf("\treturn e.On(%s, func(event Event, control EventControl) {", declared.ConstName()))
	file.P(fmt.Sprintf("\t\tif typed, ok := event.(*%s); ok {", class))
	file.P("\t\t\thandler(typed, control)")
	file.P("\t\t}")
	file.P("\t})")
	file.P("}")
	file.P()

	return sdkDecoder(file, declared)
}

// sdkDecoder writes the reader for one event's positional payload.
func sdkDecoder(file *protogen.GeneratedFile, declared event) error {
	class := declared.SDKType()

	file.P(fmt.Sprintf("func %s(fields []abi.Value, sink *effects) (*%s, error) {",
		declared.SDKDecoder(), class))
	file.P(fmt.Sprintf("\tif len(fields) != %d {", len(declared.Fields)))
	file.P(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"gocraft: %s has %%d fields, want %d\", len(fields))",
		declared.Type, len(declared.Fields)))
	file.P("\t}")

	assignments := make([]string, 0, len(declared.Fields))
	for _, f := range declared.Fields {
		value := fmt.Sprintf("fields[%d]", f.Index)
		description := fmt.Sprintf("%q", declared.Type+" "+f.Name)

		decode := ""
		local := ""
		if f.Injected {
			decode, local = "permissionsFrom({v})", "permissions"
		} else {
			binding, err := bindingFor(f.Kind)
			if err != nil {
				return fmt.Errorf("%s.%s: %w", declared.Type, f.Name, err)
			}
			if binding.SDKDecode == "" {
				return fmt.Errorf("%s.%s: no plugin-side Go decoder for %q; add one to "+
					"cmd/protoc-gen-gocraft/vocabulary.go", declared.Type, f.Name, f.Kind)
			}
			decode, local = binding.SDKDecode, lowerFirst(f.GoName())
			assignments = append(assignments, fmt.Sprintf("%s: %s", f.GoName(), local))
		}
		expression := strings.NewReplacer("{v}", value, "{d}", description).Replace(decode)
		file.P(fmt.Sprintf("\t%s, err := %s", local, expression))
		file.P("\tif err != nil {")
		file.P("\t\treturn nil, err")
		file.P("\t}")
	}
	if _, ok := declared.Permissions(); ok {
		assignments = append(assignments, "permissions: permissions")
	}
	file.P(fmt.Sprintf("\treturn &%s{%s}, nil", class, strings.Join(assignments, ", ")))
	file.P("}")
	file.P()
	return nil
}

// sdkDispatch writes the one place a wire event becomes a typed one.
//
// Generated rather than written beside the decoders, so an event added to the
// schema cannot arrive with a reader and no route to it.
func sdkDispatch(file *protogen.GeneratedFile, events []event) error {
	file.P("// eventFrom reads one dispatched event.")
	file.P("//")
	file.P("// A native event is decoded against the layout generated with it. Anything")
	file.P("// else is plugin-defined by construction — a provided type must contain a")
	file.P("// slash and no native name has one — so it goes to the positional reader")
	file.P("// rather than being refused. Which layout it should be read against is a")
	file.P("// fact this build cannot have: it belongs to the manifest of whichever")
	file.P("// plugin provides it.")
	file.P("func eventFrom(incoming *abi.Event, sink *effects) (Event, error) {")
	file.P("\tif incoming == nil {")
	file.P("\t\treturn nil, fmt.Errorf(\"gocraft: missing event\")")
	file.P("\t}")
	file.P("\tswitch incoming.Type {")
	for _, declared := range events {
		file.P(fmt.Sprintf("\tcase %s:", declared.ConstName()))
		file.P(fmt.Sprintf("\t\treturn %s(incoming.Fields, sink)", declared.SDKDecoder()))
	}
	file.P("\tdefault:")
	file.P("\t\treturn customFrom(incoming)")
	file.P("\t}")
	file.P("}")
	return nil
}

// sdkDoc is the sentence that says how an event behaves, in the terms a plugin
// author cares about.
func sdkDoc(declared event) string {
	if declared.Observational {
		return "Observational: the tick does not wait, and nothing a handler does\n" +
			"can prevent what already happened."
	}
	return "Cancellable, and dispatched while the tick waits. Every subscriber\n" +
		"shares one budget for the whole event, so a handler that takes its\n" +
		"time is taking it from the others."
}
